### ISSUE TITLE
Needs update to webpack 2

### ISSUE THREAD

**Issue by ben-yocum** [bestander/uglify-loader#13]
Users following the example in the README will get an error:

`For loader options: webpack 2 no longer allows custom properties in configuration.
  Loaders should be updated to allow passing options via loader options in module.rules.
  Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
  plugins: [
    new webpack.LoaderOptionsPlugin({
      // test: /\.xxx$/, // may apply this only for some modules
      options: {
        uglify-loader: ...
      }
    })
  ]`

Webpack 2 uses a different method for module configuration. There are other differences as well. I don't know how many of them are impactful.

I'm willing to figure this one out and submit a pull request, but first I need to know if this loader is still actively maintained.

**Comment by bestander** [comment]
Thanks for raising this.

Please send a PR.
And feel free to take over maintenance if you want to do it.

**Comment by ben-yocum** [comment]
Alright. I'll get it fixed by next week.

I'll consider taking over maintenance and let you know later.

**Comment by osela** [comment]
Should be fixed by #15
