### ISSUE TITLE
Doesn't work with uglify-js@2.7.5

### ISSUE THREAD

**Issue by dizel3d** [bestander/uglify-loader#14]
https://github.com/bestander/uglify-loader/blob/master/index.js#L55
result.map is undefined for uglify-js@2.7.5

**Comment by bestander** [comment]
PR is welcome :)

**Comment by bestander** [comment]
Switched to uglify-js 3.x.
I think this is not relevant anymore https://github.com/bestander/uglify-loader/pull/16
