### ISSUE TITLE
How to chain with script-loader?

### ISSUE THREAD

**Issue by DanielApt** [bestander/uglify-loader#2]
I'd like to use uglify-loader to uglify files required with the [`script-loader`](https://github.com/webpack/script-loader).

My code looks as follows:

```
require('uglify-loader');
require('uglify!script!../lib/form2js/form2js');
```

When doing this I get the following error:

```
Module not found: Error: Cannot resolve module 'fs'
in ~/project/node_modules/uglify-loader/node_modules/uglify-js/tools
 @ ./~/uglify-loader/~/uglify-js/tools/node.js 2:9-22
```

**Comment by bestander** [comment]
Why do you require `require('uglify-loader');`?
Webpack plugins should work without explicit require.

I just have checked it on my local setup:

```
[169] ./~/uglify-loader!./~/script-loader!./components/angular/angular.min.js 386 {0} [built]
[170] ./~/raw-loader!./components/angular/angular.min.js 128453 {0} [built]
```

All looks fine to me.

This `Cannot resolve module 'fs'` is familiar, have a look at 
https://github.com/webpack/webpack/issues/451
https://github.com/webpack/jade-loader/issues/8

**Comment by bestander** [comment]
reopen issue if it is still relevant
