### ISSUE TITLE
Support for source maps

### ISSUE THREAD

**Issue by wattsbn** [bestander/uglify-loader#3]
When I use the UglifyJsPlugin the generated source maps contain the original (un-uglified) code. However, when I use this loader, the source maps contain the uglified code.

I really like this loader because it gives me better flexibility that the plugin, but I would still like to have useful source maps.

**Comment by bestander** [comment]
Thanks for liking it, for this exact reason I have created it.

The loader is very primitive, just 5 lines of code, I'll see how to configure it to retain source maps, should be easy.

**Comment by bestander** [comment]
I've started a PR https://github.com/bestander/uglify-loader/pull/4. I am going to test it later in the week but if you can test with your setup I would appreciate it.

**Comment by wattsbn** [comment]
I should be able to test it out later today. Thanks for the quick response.

**Comment by wattsbn** [comment]
I am getting an error while trying to run your changes.
`content is not defined`

I tried changing `content` to `source`. That made the build work, but it did not produce the correct source maps.

**Comment by bestander** [comment]
Thanks,  I'll be tweaking it more today

**Comment by bestander** [comment]
@wattsbn, should be fixed in version 1.2.0.
