### ISSUE TITLE
How is this different from UglifyJsPlugin using mangle.except?

### ISSUE THREAD

**Issue by peter-mouland** [bestander/uglify-loader#6]
http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin

**Comment by bestander** [comment]
This loader was built before mangle.except option was available in UglifyJsPlugin. 
The loader works at different granularity, per every required file while plugin works during bundling.

I guess some people may find it useful though for most users UglifyJsPlugin would be sufficient.

Thanks for pointing it out
